//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartView
    {
        public int Cart_id { get; set; }
        public string Product_code { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public int Order_id { get; set; }
        public string Product_name { get; set; }
    }
}
