//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Delivery_id { get; set; }
        public string Track_number { get; set; }
        public string Phone { get; set; }
        public string Delivery_type { get; set; }
        public System.DateTime Delivery_date { get; set; }
        public int Order_id { get; set; }
        public string Statuse_code { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
    }
}
