//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryView
    {
        public string Track_number { get; set; }
        public Nullable<System.DateTime> Order_date { get; set; }
        public System.DateTime Delivery_date { get; set; }
        public Nullable<decimal> Total_cost { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public string Delivery_type { get; set; }
        public string Login { get; set; }
        public string Adress { get; set; }
    }
}
