//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersView
    {
        public int Order_id { get; set; }
        public string Order_number { get; set; }
        public System.DateTime Order_date { get; set; }
        public System.DateTime Completion_date { get; set; }
        public decimal Total_cost { get; set; }
        public decimal Paid { get; set; }
        public string Full_name { get; set; }
        public string Discount_card { get; set; }
        public string Statuse_name { get; set; }
        public string Cancellation_sign { get; set; }
    }
}
