//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductView
    {
        public string Order_number { get; set; }
        public string Product_name { get; set; }
        public string Category_name { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public string Login { get; set; }
    }
}
