//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellsView
    {
        public Nullable<int> Year { get; set; }
        public string Category_name { get; set; }
        public Nullable<int> Sells { get; set; }
        public Nullable<decimal> Sum { get; set; }
    }
}
